profiles:
  - label: "LinkedIn"
    href: "https://www.linkedin.com/in/corey-m-abramson-328926153"
    rel: "me"
  - label: "Personal site"
    href: "https://cmabramson.com"
    rel: "me"
  - label: "Lab GitHub"
    href: "https://github.com/Computational-Ethnography-Lab"
    rel: ""
  - label: "Google Scholar"
    href: "https://scholar.google.com/citations?user=vBMsaYwAAAAJ&hl=en"
    rel: "me"
  - label: "My Bibliography"
    href: "https://www.ncbi.nlm.nih.gov/myncbi/corey.abramson.1/bibliography/public/"
    rel: "me"
